### ISSUE TITLE
Option to show more slides per page

### ISSUE THREAD

**Issue by vabatta** [dbismut/react-soft-slider#8]
Hi,

I was wondering how can I achieve that you can show like n slides at a time rather than just a single one.

**Comment by dbismut** [comment]
Depends on what you want to achieve. If it's just a matter of size, you can style the slides relatively to their container like so:

https://codesandbox.io/s/react-soft-slider-example-71pze

The slider centers the slides in the wrapper, and there is no currently way to customize this, although this could be easily fixable.

If you want to move slides 2 by 2, that's something that this slider doesn't allow yet.

**Comment by vabatta** [comment]
Yeah, I was able to dynamically size them based on a parent container but I was looking for a way to sort of 'bound' where and when a slide should be able to move at a time. Example: if you I style my slides to be equally divided into 2 slides per carousel view port (the size of the container), the problem is that the actual snap point for the slide to fit in is going always to be half of it (you can scroll such that the last item is going to be all on the left and have the right side empty); I was trying to tweak the `onIndexChange` but unsuccessfully. Demo: https://codesandbox.io/s/react-soft-slider-example-h0kor

**Comment by dbismut** [comment]
Yes so you want the snap point to be aligned on the left instead of center is that correct? But still move 1 slide per swipe right?

**Comment by vabatta** [comment]
No, I want that the last slide that get in the screen get snapped and doesnt allow you to drag it anymore. Lets take the example I sent above: 9 slides that get 50 % of my view port; when i drag them, the 8th should be the last one that snaps in the box, and the ninth should be filling the screen (and be locked and impossible to scroll, so that you cannot achieve it to be on the left and have the right side - potentially 10th - to be invisible)

**Comment by vabatta** [comment]
You can look at the updated demo: https://codesandbox.io/s/react-soft-slider-example-h0kor

**Comment by dbismut** [comment]
@vabatta ok got you, I think I know why this might fail, let me have a look.

Btw, I see that you would like to have an option to style `.wrapper > div`. This is an option that you would like to pass as a prop to the slider right? Could be a class or style.

**Comment by dbismut** [comment]
@vabatta ok so just released `2.1.2` that has two additional props:

- `rootStyle` to allow styling the inner div component
- `indexRange` that declaratively limits the range of indexes the slider can slide through

Have a look at: https://codesandbox.io/s/react-soft-slider-example-o7k0gx

Just to give you a clearer understanding of how the slider inner logic works, let me explain how I built it originally (not saying this is the best way to do it, feel free to criticize).

Where most sliders have a inner `index` state, this slider only has a inner `indexRef` ref.

Every time it detects that the user wants to drag to another index (this is just math, ie the user has dragged the slider a certain distance or swiped with a certain velocity), it updates `indexRef` and asks the user to update the `index` prop to be equal to `indexRef`. As you might have guessed, the argument of `onIndexChange` is `indexRef`.

At this point, the slider might not be rested (ie it's in the middle of a drag), but it doesn't care, since _in theory_ the user _should_ update the `index` prop to match the `indexRef` and this _will_ trigger a re-render of the slider.

Every time the slider renders, it moves the slides where they should be based on the `index` prop.

In your case, you had to force render the slider for your logic to work as you wanted. Your ideal logic would be to ignore responding to `onIndexChange` when its argument (ie `indexRef` is superior to `7`).

But by **NOT** setting `onIndexChange` you prevent the slider from re-rendering, and therefore it wasn't able to sync the slide positions to the `index` prop. So you had to force a re-render (this is essentially what you did by setting the `index` to `6` and then back to `7`.

Anyway, with the `indexRange` option, `indexRef` won't update to indexes off bounds!

Hope it helps!

**Comment by vabatta** [comment]
Yeah, I did imagine that by setting the index twice I was forcing the slider to re-render. I am still not sure if this is the best way to accomplish the carousel, but keeps the logic somewhat simple. Also, I think that the outer div (https://github.com/dbismut/react-soft-slider/blob/master/src/index.tsx#L313) is unnecessary.

**Comment by dbismut** [comment]
@vabatta did you check the example I sent? this should fix what you want to do without re-rendering.

> Also, I think that the outer div is unnecessary.

The outer div is there by commodity, since it's usually easier for users to position and size `display: block` div where the inner div is `display: flex`. I'll try to release a version without the outer div and see where this leads it.

**Comment by dbismut** [comment]
`2.2.0` is out and removes the outer div.

**Comment by vabatta** [comment]
@dbismut yes, the example with the range does the job. I am still tweaking for an even different case but I think that with all this many things now is it possible to achieve all sort of things. I was thinking that the div was just for commodity but I would rather change and wrap myself rather than passing inline styles. Cool, I will check out all the new changes.

**Comment by dbismut** [comment]
Ok great. At the moment I’ve set the former inner div (which is now the outer div) width to 100%. But I might as well remove this. I want to be this slider as flexible as possible so let me know if there’s anything that goes in the way. 

And feel free to submit a PR if you feel up to it!

**Comment by vabatta** [comment]
Definitely will do that. I will try different use cases and do some pull requests for new things :)
